// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package queries

import (
	"context"
)

const checkReady = `-- name: CheckReady :one
SELECT 1::integer AS healthy
`

func (q *Queries) CheckReady(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkReady)
	var healthy int32
	err := row.Scan(&healthy)
	return healthy, err
}
