// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPaymentReady = `-- name: CheckPaymentReady :one
SELECT (SELECT count(*) FROM payment_orders WHERE false)+(SELECT count(*) FROM payment_operations WHERE false)+(SELECT count(*) FROM payment_request_bindings WHERE false)+(SELECT count(*) FROM payment_history WHERE false) AS relation_count
`

func (q *Queries) CheckPaymentReady(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkPaymentReady)
	var relation_count int32
	err := row.Scan(&relation_count)
	return relation_count, err
}

const claimPaymentDispatch = `-- name: ClaimPaymentDispatch :exec
UPDATE payment_operations SET state='unresolved',snapshot=$2,version=version+1,owner_token=$3,prior_ambiguity=true,first_dispatch_at=$4,last_dispatch_at=$5,dispatch_expires_at=$6,lease_until=clock_timestamp()+interval '12 seconds',updated_at=$5 WHERE id=$1
`

type ClaimPaymentDispatchParams struct {
	ID                pgtype.UUID
	Snapshot          []byte
	OwnerToken        string
	FirstDispatchAt   pgtype.Timestamptz
	LastDispatchAt    pgtype.Timestamptz
	DispatchExpiresAt pgtype.Int8
}

func (q *Queries) ClaimPaymentDispatch(ctx context.Context, arg ClaimPaymentDispatchParams) error {
	_, err := q.db.Exec(ctx, claimPaymentDispatch,
		arg.ID,
		arg.Snapshot,
		arg.OwnerToken,
		arg.FirstDispatchAt,
		arg.LastDispatchAt,
		arg.DispatchExpiresAt,
	)
	return err
}

const insertPaymentBinding = `-- name: InsertPaymentBinding :exec
INSERT INTO payment_request_bindings(request_key,method,target,order_id,operation_id,description,amount,currency,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertPaymentBindingParams struct {
	RequestKey  pgtype.UUID
	Method      string
	Target      string
	OrderID     pgtype.UUID
	OperationID pgtype.UUID
	Description string
	Amount      int64
	Currency    string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertPaymentBinding(ctx context.Context, arg InsertPaymentBindingParams) error {
	_, err := q.db.Exec(ctx, insertPaymentBinding,
		arg.RequestKey,
		arg.Method,
		arg.Target,
		arg.OrderID,
		arg.OperationID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.CreatedAt,
	)
	return err
}

const insertPaymentHistory = `-- name: InsertPaymentHistory :exec
INSERT INTO payment_history(order_id,sequence,kind,recorded_at,operation_id,from_state,to_state,stripe_session_id,stripe_payment_intent_id,stripe_event_id,stripe_request_id,failure_code,event_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type InsertPaymentHistoryParams struct {
	OrderID               pgtype.UUID
	Sequence              int64
	Kind                  string
	RecordedAt            pgtype.Timestamptz
	OperationID           pgtype.UUID
	FromState             pgtype.Text
	ToState               pgtype.Text
	StripeSessionID       pgtype.Text
	StripePaymentIntentID pgtype.Text
	StripeEventID         pgtype.Text
	StripeRequestID       pgtype.Text
	FailureCode           pgtype.Text
	EventAt               pgtype.Timestamptz
}

func (q *Queries) InsertPaymentHistory(ctx context.Context, arg InsertPaymentHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPaymentHistory,
		arg.OrderID,
		arg.Sequence,
		arg.Kind,
		arg.RecordedAt,
		arg.OperationID,
		arg.FromState,
		arg.ToState,
		arg.StripeSessionID,
		arg.StripePaymentIntentID,
		arg.StripeEventID,
		arg.StripeRequestID,
		arg.FailureCode,
		arg.EventAt,
	)
	return err
}

const insertPaymentOperation = `-- name: InsertPaymentOperation :exec
INSERT INTO payment_operations(id,order_id,state,stripe_key,snapshot,version,owner_token,prior_ambiguity,evidence_source,investigation_required,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type InsertPaymentOperationParams struct {
	ID                    pgtype.UUID
	OrderID               pgtype.UUID
	State                 string
	StripeKey             string
	Snapshot              []byte
	Version               int64
	OwnerToken            string
	PriorAmbiguity        bool
	EvidenceSource        string
	InvestigationRequired bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertPaymentOperation(ctx context.Context, arg InsertPaymentOperationParams) error {
	_, err := q.db.Exec(ctx, insertPaymentOperation,
		arg.ID,
		arg.OrderID,
		arg.State,
		arg.StripeKey,
		arg.Snapshot,
		arg.Version,
		arg.OwnerToken,
		arg.PriorAmbiguity,
		arg.EvidenceSource,
		arg.InvestigationRequired,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPaymentOrder = `-- name: InsertPaymentOrder :exec
INSERT INTO payment_orders(id,description,amount,currency,payment_status,current_operation_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertPaymentOrderParams struct {
	ID                 pgtype.UUID
	Description        string
	Amount             int64
	Currency           string
	PaymentStatus      string
	CurrentOperationID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertPaymentOrder(ctx context.Context, arg InsertPaymentOrderParams) error {
	_, err := q.db.Exec(ctx, insertPaymentOrder,
		arg.ID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.PaymentStatus,
		arg.CurrentOperationID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const lockPaymentOperations = `-- name: LockPaymentOperations :many
SELECT to_jsonb(p) AS data, (lease_until IS NULL OR lease_until<=clock_timestamp())::boolean AS lease_expired FROM payment_operations p WHERE order_id=$1 ORDER BY id FOR UPDATE
`

type LockPaymentOperationsRow struct {
	Data         []byte
	LeaseExpired bool
}

func (q *Queries) LockPaymentOperations(ctx context.Context, orderID pgtype.UUID) ([]LockPaymentOperationsRow, error) {
	rows, err := q.db.Query(ctx, lockPaymentOperations, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockPaymentOperationsRow
	for rows.Next() {
		var i LockPaymentOperationsRow
		if err := rows.Scan(&i.Data, &i.LeaseExpired); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentOrder = `-- name: LockPaymentOrder :one
SELECT to_jsonb(o) AS data FROM payment_orders o WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockPaymentOrder(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockPaymentOrder, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const nextPaymentSequence = `-- name: NextPaymentSequence :one
UPDATE payment_orders SET history_sequence=history_sequence+1 WHERE id=$1 RETURNING history_sequence
`

func (q *Queries) NextPaymentSequence(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextPaymentSequence, id)
	var history_sequence int64
	err := row.Scan(&history_sequence)
	return history_sequence, err
}

const paymentBinding = `-- name: PaymentBinding :one
SELECT to_jsonb(b) AS binding_data,to_jsonb(o) AS order_data,to_jsonb(p) AS operation_data,coalesce(p.lease_until<=clock_timestamp(),false)::boolean AS lease_expired FROM payment_request_bindings b JOIN payment_orders o ON o.id=b.order_id JOIN payment_operations p ON p.id=b.operation_id WHERE b.request_key=$1
`

type PaymentBindingRow struct {
	BindingData   []byte
	OrderData     []byte
	OperationData []byte
	LeaseExpired  bool
}

func (q *Queries) PaymentBinding(ctx context.Context, requestKey pgtype.UUID) (PaymentBindingRow, error) {
	row := q.db.QueryRow(ctx, paymentBinding, requestKey)
	var i PaymentBindingRow
	err := row.Scan(
		&i.BindingData,
		&i.OrderData,
		&i.OperationData,
		&i.LeaseExpired,
	)
	return i, err
}

const paymentHistory = `-- name: PaymentHistory :many
SELECT to_jsonb(h) AS data FROM payment_history h WHERE order_id=$1 AND sequence>$2 ORDER BY sequence LIMIT $3
`

type PaymentHistoryParams struct {
	OrderID  pgtype.UUID
	Sequence int64
	Limit    int32
}

func (q *Queries) PaymentHistory(ctx context.Context, arg PaymentHistoryParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, paymentHistory, arg.OrderID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentOrder = `-- name: PaymentOrder :one
SELECT to_jsonb(o) AS data FROM payment_orders o WHERE id=$1
`

func (q *Queries) PaymentOrder(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, paymentOrder, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const paymentView = `-- name: PaymentView :one
SELECT to_jsonb(o) AS order_data,to_jsonb(p) AS operation_data,coalesce(p.lease_until<=clock_timestamp(),false)::boolean AS lease_expired FROM payment_orders o JOIN payment_operations p ON p.id=o.current_operation_id WHERE o.id=$1
`

type PaymentViewRow struct {
	OrderData     []byte
	OperationData []byte
	LeaseExpired  bool
}

func (q *Queries) PaymentView(ctx context.Context, id pgtype.UUID) (PaymentViewRow, error) {
	row := q.db.QueryRow(ctx, paymentView, id)
	var i PaymentViewRow
	err := row.Scan(&i.OrderData, &i.OperationData, &i.LeaseExpired)
	return i, err
}

const releasePaymentClaim = `-- name: ReleasePaymentClaim :exec
UPDATE payment_operations SET owner_token='',version=version+1,updated_at=clock_timestamp() WHERE id=$1
`

func (q *Queries) ReleasePaymentClaim(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releasePaymentClaim, id)
	return err
}

const savePaymentObservation = `-- name: SavePaymentObservation :exec
UPDATE payment_operations SET state=$2,stripe_session_id=$3,stripe_payment_intent_id=$4,checkout_url=$5,expires_at=$6,prior_ambiguity=$7,evidence_source=$8,failure_code=$9,investigation_required=$10,last_observed_at=$11,stripe_request_id=$12,owner_token='',version=version+1,updated_at=$11 WHERE id=$1
`

type SavePaymentObservationParams struct {
	ID                    pgtype.UUID
	State                 string
	StripeSessionID       pgtype.Text
	StripePaymentIntentID pgtype.Text
	CheckoutUrl           pgtype.Text
	ExpiresAt             pgtype.Timestamptz
	PriorAmbiguity        bool
	EvidenceSource        string
	FailureCode           pgtype.Text
	InvestigationRequired bool
	LastObservedAt        pgtype.Timestamptz
	StripeRequestID       pgtype.Text
}

func (q *Queries) SavePaymentObservation(ctx context.Context, arg SavePaymentObservationParams) error {
	_, err := q.db.Exec(ctx, savePaymentObservation,
		arg.ID,
		arg.State,
		arg.StripeSessionID,
		arg.StripePaymentIntentID,
		arg.CheckoutUrl,
		arg.ExpiresAt,
		arg.PriorAmbiguity,
		arg.EvidenceSource,
		arg.FailureCode,
		arg.InvestigationRequired,
		arg.LastObservedAt,
		arg.StripeRequestID,
	)
	return err
}

const setCurrentPaymentOperation = `-- name: SetCurrentPaymentOperation :exec
UPDATE payment_orders SET current_operation_id=$2,updated_at=$3 WHERE id=$1
`

type SetCurrentPaymentOperationParams struct {
	ID                 pgtype.UUID
	CurrentOperationID pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) SetCurrentPaymentOperation(ctx context.Context, arg SetCurrentPaymentOperationParams) error {
	_, err := q.db.Exec(ctx, setCurrentPaymentOperation, arg.ID, arg.CurrentOperationID, arg.UpdatedAt)
	return err
}
